
import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { useRef, useState } from 'react'
import useAuth from '../hooks/useAuth'
import { db } from '../lib/firebase'

import useOnClickOutside from '../hooks/useOnClickOutside'
import PrimaryButton from '../components/button'
import EmojiPicker from '../components/emojipicker'


// const Button = dynamic<EmojiProps>(import("../components/emojipicker"));


const Home: NextPage = () => {
  const { user, logout } = useAuth()
  const [message, setMessage] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [showEmojis, setShowEmojis] = useState(false);
  const emojiRef = useRef(null)
  const sendPost = async () => {
    setLoading(true)

    const doc = await addDoc(collection(db, 'posts'), {
      message,
      timestamp: serverTimestamp()
    })

    console.log(doc)
  }

  const selectEmoji = (event: any, emojiObject: any) => {
    console.log(emojiObject)
    setMessage(message + emojiObject.emoji)
  }

  useOnClickOutside(emojiRef, () => {setShowEmojis(false)});

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container m-auto'>
        <div className='grid grid-cols-4'>
          <div>
            <ul>
              <li>
                <Link href={'/'}>Home</Link>
              </li>
            </ul>
            {user && <button onClick={async () => {
              await logout()
            }}>Logout</button>}
          </div>
          <div className='col-span-2'>
            <div className='message-form'>
              <textarea name="message" value={message} onChange={(e) => setMessage(e.target.value)} />
              

              <EmojiPicker onEmojiClick={selectEmoji} />
              <PrimaryButton label='Send Message' onClick={sendPost} disabled={!message}/>
            </div>
          </div>
          <div>
            Right bar
          </div>
        </div>
      </div>
    </div>
  )
}

export default Home
